apiVersion: v1
description: EFK(Elasticsearch + Filebeat + Kibana)
name: efk
version: 7.13.4
appVersion: 7.13.4
icon: file://../efk-logo.jpg
sources:
- https://www.elastic.co/products/elasticsearch
- https://www.elastic.co/products/kibana
- https://fluentbit.io/
home: https://www.elastic.co
maintainers:
- name: guangbochen
  email: support@rancher.com
engine: gotpl
