# Default values for efk.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
elasticsearch:
  enabled: true
  image: "docker.io/library/elasticsearch"
  imageTag: "7.13.4"
  enableProxy: true


kibana:
  enabled: true
  image: "docker.elastic.co/kibana/kibana"
  imageTag: "7.13.4"

filebeat:
  enabled: true
  image: "docker.elastic.co/beats/filebeat"
  imageTag: "7.13.4"

metricbeat:
  enabled: true
  image: "docker.elastic.co/beats/metricbeat"
  imageTag: "7.13.4"
  kube-state-metrics:
    image:
      repository: ranchercharts/coreos-kube-state-metrics
      tag: v1.7.2

global:
  nginxProxy:
    repository: rancher/nginx
    tag: 1.15.8-alpine
